# -*- coding: utf-8 -*-
'''
Created on 2009-10-29

@author: marcin
'''

LANGUAGE_CODES_MAPPINGS = {
    'en': 'en_GB',
}

#Generated with languages module
LANGUAGE_CODES = {
    "_IN"  : "Manipuri",
    "aa_ET" : "Afar",
    "ab_GE" : "Abkhazian",
    "af_ZA" : "Afrikaans",
    "am_ET" : "Amharic",
    "ar_AE" : "Arabic (Uae)",
    "ar_BH" : "Arabic (Bahrain)",
    "ar_DZ" : "Arabic (Algeria)",
    "ar_EG" : "Arabic (Egypt)",
    "ar_IQ" : "Arabic (Iraq)",
    "ar_JO" : "Arabic (Jordan)",
    "ar_KW" : "Arabic (Kuwait)",
    "ar_LB" : "Arabic (Lebanon)",
    "ar_LY" : "Arabic (Libya)",
    "ar_MA" : "Arabic (Morocco)",
    "ar_OM" : "Arabic (Oman)",
    "ar_QA" : "Arabic (Qatar)",
    "ar_SA" : "Arabic (Saudi Arabia)",
    "ar_SD" : "Arabic (Sudan)",
    "ar_SY" : "Arabic (Syria)",
    "ar_TN" : "Arabic (Tunisia)",
    "ar_YE" : "Arabic (Yemen)",
    "as_IN" : "Assamese",
    "ay_BO" : "Aymara",
    "az_AZ" : "Azeri (Latin)",
    "ba_RU" : "Bashkir",
    "be_BY" : "Belarusian",
    "bg_BG" : "Bulgarian",
    "bh_IN" : "Bihari",
    "bi_VU" : "Bislama",
    "bn_IN" : "Bengali",
    "bo_CN" : "Tibetan",
    "br_FR" : "Breton",
    "ca_ES" : "Catalan",
    "ca_ES@valencia" : "Valencian",
    "co_FR" : "Corsican",
    "cs_CZ" : "Czech",
    "cy_GB" : "Welsh",
    "da_DK" : "Danish",
    "de_AT" : "German (Austrian)",
    "de_BE" : "German (Belgium)",
    "de_CH" : "German (Swiss)",
    "de_DE" : "German",
    "de_LI" : "German (Liechtenstein)",
    "de_LU" : "German (Luxembourg)",
    "dz_BT" : "Bhutani",
    "el_GR" : "Greek",
    "en_AU" : "English (Australia)",
    "en_BW" : "English (Botswana)",
    "en_BZ" : "English (Belize)",
    "en_CA" : "English (Canada)",
    "en_CB" : "English (Caribbean)",
    "en_DK" : "English (Denmark)",
    "en_GB" : "English",
    "en_IE" : "English (Eire)",
    "en_JM" : "English (Jamaica)",
    "en_NZ" : "English (New Zealand)",
    "en_PH" : "English (Philippines)",
    "en_TT" : "English (Trinidad)",
    "en_US" : "English (U.S.)",
    "en_ZA" : "English (South Africa)",
    "en_ZW" : "English (Zimbabwe)",
    "eo_ESPERANTO" : "Esperanto",
    "es_AR" : "Spanish (Argentina)",
    "es_BO" : "Spanish (Bolivia)",
    "es_CL" : "Spanish (Chile)",
    "es_CO" : "Spanish (Colombia)",
    "es_CR" : "Spanish (Costa Rica)",
    "es_DO" : "Spanish (Dominican republic)",
    "es_EC" : "Spanish (Ecuador)",
    "es_ES" : "Spanish (Modern)",
    "es_GT" : "Spanish (Guatemala)",
    "es_HN" : "Spanish (Honduras)",
    "es_MX" : "Spanish (Mexican)",
    "es_NI" : "Spanish (Nicaragua)",
    "es_PA" : "Spanish (Panama)",
    "es_PE" : "Spanish (Peru)",
    "es_PR" : "Spanish (Puerto Rico)",
    "es_PY" : "Spanish (Paraguay)",
    "es_SV" : "Spanish (El Salvador)",
    "es_US" : "Spanish (U.S.)",
    "es_UY" : "Spanish (Uruguay)",
    "es_VE" : "Spanish (Venezuela)",
    "et_EE" : "Estonian",
    "eu_ES" : "Basque",
    "fa_IR" : "Farsi",
    "fi_FI" : "Finnish",
    "fj_FJ" : "Fiji",
    "fo_FO" : "Faeroese",
    "fr_BE" : "French (Belgian)",
    "fr_CA" : "French (Canadian)",
    "fr_CH" : "French (Swiss)",
    "fr_FR" : "French",
    "fr_LU" : "French (Luxembourg)",
    "fr_MC" : "French (Monaco)",
    "fy_NL" : "Frisian",
    "ga_IE" : "Irish",
    "gd_GB" : "Scots Gaelic",
    "gl_ES" : "Galician",
    "gn_PY" : "Guarani",
    "gu_IN" : "Gujarati",
    "ha_NG" : "Hausa",
    "he_IL" : "Hebrew",
    "hi_IN" : "Hindi",
    "hr_HR" : "Croatian",
    "hu_HU" : "Hungarian",
    "hy_AM" : "Armenian",
    "ia_US" : "Interlingua",
    "id_ID" : "Indonesian",
    "ie_US" : "Interlingue",
    "ik_US" : "Inupiak",
    "is_IS" : "Icelandic",
    "it_CH" : "Italian (Swiss)",
    "it_IT" : "Italian",
    "iu_CA" : "Inuktitut",
    "ja_JP" : "Japanese",
    "jw_IN" : "Javanese",
    "ka_GE" : "Georgian",
    "kk_KZ" : "Kazakh",
    "kl_GL" : "Greenlandic",
    "km_KH" : "Cambodian",
    "kn_IN" : "Kannada",
    "ko_KR" : "Korean",
    "ks_IN" : "Kashmiri (India)",
    "ku_IQ" : "Kurdish",
    "kw_GB" : "Kernewek",
    "ky_KG" : "Kirghiz",
    "la_VA" : "Latin",
    "ln_CD" : "Lingala",
    "lo_LA" : "Laothian",
    "lt_LT" : "Lithuanian",
    "lv_LV" : "Latvian",
    "mg_MG" : "Malagasy",
    "mi_NZ" : "Maori",
    "mk_MK" : "Macedonian",
    "ml_IN" : "Malayalam",
    "mn_MN" : "Mongolian",
    "mo_MD" : "Moldavian",
    "mr_IN" : "Marathi",
    "ms_BN" : "Malay (Brunei Darussalam)",
    "ms_MY" : "Malay (Malaysia)",
    "mt_MT" : "Maltese",
    "my_MM" : "Burmese",
    "na_NR" : "Nauru",
    "nb_NO" : "Norwegian (Bokmal)",
    "ne_IN" : "Nepali (India)",
    "ne_NP" : "Nepali",
    "nl_BE" : "Dutch (Belgian)",
    "nl_NL" : "Dutch",
    "nn_NO" : "Norwegian (Nynorsk)",
    "oc_FR" : "Occitan",
    "om_ET" : "(Afan) Oromo",
    "or_IN" : "Oriya",
    "pa_IN" : "Punjabi",
    "pl_PL" : "Polish",
    "ps_AF" : "Pashto, Pushto",
    "pt_BR" : "Portuguese (Brazilian)",
    "pt_PT" : "Portuguese",
    "qu_BO" : "Quechua",
    "rm_CH" : "Rhaeto-Romance",
    "rn_BI" : "Kirundi",
    "ro_RO" : "Romanian",
    "ru_RU" : "Russian",
    "ru_UA" : "Russian (Ukraine)",
    "rw_RW" : "Kinyarwanda",
    "sa_IN" : "Sanskrit",
    "sd_PK" : "Sindhi",
    "se_NO" : "Northern Sami",
    "sg_CF" : "Sangho",
    "sh_HR" : "Serbo-Croatian",
    "si_IN" : "Sinhalese",
    "sk_SK" : "Slovak",
    "sl_SI" : "Slovenian",
    "sm_WS" : "Samoan",
    "sn_ZW" : "Shona",
    "so_SB" : "Somali",
    "sq_AL" : "Albanian",
    "sr_YU" : "Serbian (Latin)",
    "ss_SZ" : "Siswati",
    "st_ZA" : "Sesotho",
    "su_SD" : "Sundanese",
    "sv_FI" : "Swedish (Finland)",
    "sv_SE" : "Swedish",
    "sw_KE" : "Swahili",
    "ta_IN" : "Tamil",
    "te_IN" : "Telugu",
    "tg_TJ" : "Tajik",
    "th_TH" : "Thai",
    "ti_ET" : "Tigrinya",
    "tk_TM" : "Turkmen",
    "tl_PH" : "Tagalog",
    "tn_ZA" : "Setswana",
    "to_TO" : "Tonga",
    "tr_TR" : "Turkish",
    "ts_MZ" : "Tsonga",
    "tt_RU" : "Tatar",
    "tw_GH" : "Twi",
    "ug_CN" : "Uighur",
    "uk_UA" : "Ukrainian",
    "ur_IN" : "Urdu (India)",
    "ur_PK" : "Urdu (Pakistan)",
    "uz_UZ" : "Uzbek (Latin)",
    "vi_VN" : "Vietnamese",
    "vo_VOLAPUK" : "Volapuk",
    "wo_SN" : "Wolof",
    "xh_ZA" : "Xhosa",
    "yi_IL" : "Yiddish",
    "yo_NG" : "Yoruba",
    "za_CN" : "Zhuang",
    "zh_CN" : "Chinese (Traditional)",
    "zh_HK" : "Chinese (Hongkong)",
    "zh_MO" : "Chinese (Macau)",
    "zh_SG" : "Chinese (Singapore)",
    "zh_TW" : "Chinese (Taiwan)",
    "zu_ZA" : "Zulu",
}


#ISO-639-1 codes (not used atm)
LANGUAGE_CODES_ISO_639_1 = {
'aa': 'Afar',
 'ab': 'Abkhazian',
 'ae': 'Avestan',  
 'af': 'Afrikaans',
 'ak': 'Akan',     
 'am': 'Amharic',  
 'an': 'Aragonese',
 'ar': 'Arabic',   
 'as': 'Assamese', 
 'av': 'Avaric',   
 'ay': 'Aymara',   
 'az': 'Azerbaijani',
 'ba': 'Bashkir',    
 'be': 'Belarusian', 
 'bg': 'Bulgarian',  
 'bh': 'Bihari',     
 'bi': 'Bislama',    
 'bm': 'Bambara',    
 'bn': 'Bengali',    
 'bo': 'Tibetan',    
 'br': 'Breton',     
 'bs': 'Bosnian',    
 'ca': 'Catalan,',   
 'ce': 'Chechen',    
 'ch': 'Chamorro',   
 'co': 'Corsican',   
 'cr': 'Cree',       
 'cs': 'Czech',      
 'cu': 'Church',     
 'cv': 'Chuvash',    
 'cy': 'Welsh',      
 'da': 'Danish',     
 'de': 'German',     
 'dv': 'Divehi,',    
 'dz': 'Dzongkha',   
 'ee': 'Ewe',        
 'el': 'Modern',     
 'en': 'English',    
 'eo': 'Esperanto',  
 'es': 'Spanish,',   
 'et': 'Estonian',   
 'eu': 'Basque',     
 'fa': 'Persian',    
 'ff': 'Fulah',      
 'fj': 'Fijian',     
 'fo': 'Faroese',    
 'fr': 'French',     
 'fy': 'Western',    
 'ga': 'Irish',      
 'gd': 'Gaelic,',    
 'gl': 'Galician',   
 'gn': 'Guaran\xc3\xad',
 'gu': 'Gujarati',      
 'gv': 'Manx',          
 'ha': 'Hausa',         
 'he': 'Modern',        
 'hi': 'Hindi',         
 'ho': 'Hiri',          
 'hr': 'Croatian',      
 'ht': 'Haitian,',      
 'hu': 'Hungarian',     
 'hy': 'Armenian',      
 'hz': 'Herero',        
 'ia': 'Interlingua',   
 'id': 'Indonesian',    
 'ie': 'Interlingue,',  
 'ig': 'Igbo',          
 'ii': 'Sichuan',       
 'ik': 'Inupiaq',       
 'io': 'Ido',           
 'is': 'Icelandic',     
 'it': 'Italian',       
 'ja': 'Japanese',      
 'jv': 'Javanese',      
 'ka': 'Georgian',      
 'kg': 'Kongo',         
 'ki': 'Kikuyu,',       
 'kj': 'Kwanyama,',     
 'kk': 'Kazakh',        
 'kl': 'Kalaallisut,',  
 'km': 'Central',       
 'kn': 'Kannada',       
 'ko': 'Korean',        
 'kr': 'Kanuri',        
 'ks': 'Kashmiri',      
 'ku': 'Kurdish',       
 'kv': 'Komi',          
 'kw': 'Cornish',       
 'ky': 'Kirghiz,',      
 'la': 'Latin',         
 'lb': 'Luxembourgish,',
 'lg': 'Ganda',         
 'li': 'Limburgish,',   
 'ln': 'Lingala',       
 'lo': 'Lao',           
 'lt': 'Lithuanian',    
 'lu': 'Luba-Katanga',  
 'lv': 'Latvian',       
 'mg': 'Malagasy',      
 'mh': 'Marshallese',   
 'mi': 'M\xc4\x81ori',  
 'mk': 'Macedonian',    
 'ml': 'Malayalam',     
 'mn': 'Mongolian',     
 'mr': 'Marathi',       
 'ms': 'Malay',         
 'my': 'Burmese',       
 'na': 'Nauru',         
 'nb': 'Norwegian',     
 'nd': 'North',         
 'ne': 'Nepali',        
 'ng': 'Ndonga',        
 'nl': 'Dutch,',        
 'nn': 'Norwegian',     
 'no': 'Norwegian',     
 'nr': 'South',         
 'nv': 'Navajo,',       
 'ny': 'Chichewa,',     
 'oc': 'Occitan',       
 'oj': 'Ojibwa',        
 'om': 'Oromo',         
 'or': 'Oriya',         
 'os': 'Ossetian,',     
 'pa': 'Panjabi,',      
 'pi': 'P\xc4\x81li',   
 'pl': 'Polish',        
 'ps': 'Pashto,',       
 'pt': 'Portuguese',    
 'qu': 'Quechua',       
 'rm': 'Romansh',       
 'rn': 'Rundi',         
 'ro': 'Romanian,',     
 'ru': 'Russian',       
 'rw': 'Kinyarwanda',   
 'sa': 'Sanskrit',      
 'sc': 'Sardinian',     
 'sd': 'Sindhi',        
 'se': 'Northern',      
 'sg': 'Sango',         
 'si': 'Sinhala,',      
 'sk': 'Slovak',        
 'sl': 'Slovene',       
 'sm': 'Samoan',        
 'sn': 'Shona',         
 'so': 'Somali',        
 'sr': 'Serbian',       
 'ss': 'Swati',         
 'st': 'Southern',      
 'su': 'Sundanese',     
 'sv': 'Swedish',       
 'sw': 'Swahili',       
 'ta': 'Tamil',         
 'te': 'Telugu',        
 'tg': 'Tajik',         
 'th': 'Thai',          
 'ti': 'Tigrinya',      
 'tk': 'Turkmen',       
 'tl': 'Tagalog',       
 'tn': 'Tswana',        
 'to': 'Tonga',         
 'tr': 'Turkish',       
 'ts': 'Tsonga',        
 'tt': 'Tatar',         
 'tw': 'Twi',           
 'ty': 'Tahitian',      
 'ug': 'Uighur,',       
 'uk': 'Ukrainian',     
 'ur': 'Urdu',
 'uz': 'Uzbek',
 've': 'Venda',
 'vi': 'Vietnamese',
 'vo': 'Volap\xc3\xbck',
 'wa': 'Walloon',
 'wo': 'Wolof',
 'xh': 'Xhosa',
 'yi': 'Yiddish',
 'yo': 'Yoruba',
 'za': 'Zhuang,',
 'zh': 'Chinese',
 'zu': 'Zulu'
 }
